name: angel_halo
version: 0.0.0
description: Opinionated framework, configurations, and presets on top of Angel.
homepage: https://github/angel-dart/opinionated
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  angel_framework: ^2.0.5-beta
  angel_migration: ^2.0.0
  angel_model: ^1.0.0
  angel_oauth2: ^2.0.0
  angel_orm: ^2.1.0-beta
  angel_security:
    git: https://github.com/angel-dart/security.git
  angel_serialize: ^2.0.0
  angel_validate: ^3.0.0-alpha
  dbcrypt: ^1.0.0
  pedantic: ^1.0.0
dev_dependencies:
  angel_orm_generator: ^2.1.0-beta
  angel_serialize_generator: ^2.0.0
  build_runner: ^1.0.0
